name: Example Gatus' Job (2/2) - Deploy Gatus

# FILL THE MISSING VALUES BELOW
on:
  workflow_dispatch:

env:
  AWS_REGION:
  ECR_REPOSITORY:
  ECS_CLUSTER:
  TOKEN: ${{ secrets.TOKEN }}

  ECS_GATUS_SERVICE:
  GATUS_TASK_DEFINITION:
  GATUS_URL: "??? ${{ secrets.ALB_ENDPOINT }} ???"
# FILL THE MISSING VALUES ABOVE

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # add build steps here

      - name: Update ECS task definition
        run: |
          sed -i "s|<task-def-image>|$IMAGE_FULL_URI|g" $GATUS_TASK_DEFINITION
          echo "Task definition updated."
          cat $GATUS_TASK_DEFINITION

      - name: deploy ecs task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ env.gatus_task_definition }}
          service: ${{ env.ecs_gatus_service }}
          cluster: ${{ env.ecs_cluster }}
          force-new-deployment: true
          run-task-tags: '[{"key": "", "value": ""} , ...]'
